#!/usr/bin/env bash
set -euo pipefail
cd <repo>

# Fixed, bounded operating-point sensitivity. Do not report best-of-target sweep claims.

# locked_default: current locked paper setting; balanced locality and stability
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 30 --window-stride-sec 10 --min-support-corr 0.25 --max-support-residual 1.25 --max-files 32 --jobs 8 --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --dataset-label COHFACE --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/locked_default/priors/cohface_mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/locked_default/priors/cohface_mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/locked_default/priors/cohface_mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/locked_default/priors/cohface_mahnob_target_computable_reliability_windowed.md
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 30 --window-stride-sec 10 --min-support-corr 0.25 --max-support-residual 1.25 --max-files 32 --jobs 8 --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/locked_default/priors/mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/locked_default/priors/mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/locked_default/priors/mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/locked_default/priors/mahnob_target_computable_reliability_windowed.md
cp results/final_operating_point_sensitivity/locked_default/priors/mahnob_target_computable_reliability_windowed.csv results/final_operating_point_sensitivity/locked_default/priors/mahnob_state_component_reliability_windowed.csv
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --out-run results/final_operating_point_sensitivity/locked_default/cohface --reliability-group-csv results/final_operating_point_sensitivity/locked_default/priors/cohface_mahnob_target_computable_reliability_windowed.csv --reliability-prior-scope readout_only
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/mahnob_gt_tailaligned_patch_v1/data --out-run results/final_operating_point_sensitivity/locked_default/mahnob_tailaligned --state-reliability-group-csv results/final_operating_point_sensitivity/locked_default/priors/mahnob_state_component_reliability_windowed.csv --readout-reliability-group-csv results/final_operating_point_sensitivity/locked_default/priors/mahnob_target_computable_reliability_windowed.csv
# Standalone strict regeneration omitted for lean policy: materialization writes strict metrics, and lean may not retain PKL data.
${PY:-python} scripts/run_final_operating_point_sensitivity.py --only locked_default --max-files 32 --jobs 8 --artifact-policy lean

# more_local_windows: more local target reliability; tests within-trial adaptation without new labels
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 20 --window-stride-sec 5 --min-support-corr 0.25 --max-support-residual 1.25 --max-files 32 --jobs 8 --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --dataset-label COHFACE --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/more_local_windows/priors/cohface_mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/more_local_windows/priors/cohface_mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/more_local_windows/priors/cohface_mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/more_local_windows/priors/cohface_mahnob_target_computable_reliability_windowed.md
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 20 --window-stride-sec 5 --min-support-corr 0.25 --max-support-residual 1.25 --max-files 32 --jobs 8 --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/more_local_windows/priors/mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/more_local_windows/priors/mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/more_local_windows/priors/mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/more_local_windows/priors/mahnob_target_computable_reliability_windowed.md
cp results/final_operating_point_sensitivity/more_local_windows/priors/mahnob_target_computable_reliability_windowed.csv results/final_operating_point_sensitivity/more_local_windows/priors/mahnob_state_component_reliability_windowed.csv
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --out-run results/final_operating_point_sensitivity/more_local_windows/cohface --reliability-group-csv results/final_operating_point_sensitivity/more_local_windows/priors/cohface_mahnob_target_computable_reliability_windowed.csv --reliability-prior-scope readout_only
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/mahnob_gt_tailaligned_patch_v1/data --out-run results/final_operating_point_sensitivity/more_local_windows/mahnob_tailaligned --state-reliability-group-csv results/final_operating_point_sensitivity/more_local_windows/priors/mahnob_state_component_reliability_windowed.csv --readout-reliability-group-csv results/final_operating_point_sensitivity/more_local_windows/priors/mahnob_target_computable_reliability_windowed.csv
# Standalone strict regeneration omitted for lean policy: materialization writes strict metrics, and lean may not retain PKL data.
${PY:-python} scripts/run_final_operating_point_sensitivity.py --only more_local_windows --max-files 32 --jobs 8 --artifact-policy lean

# more_stable_windows: longer reliability windows; tests whether MAHNOB needs more stable evidence aggregation
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 45 --window-stride-sec 15 --min-support-corr 0.25 --max-support-residual 1.25 --max-files 32 --jobs 8 --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --dataset-label COHFACE --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/more_stable_windows/priors/cohface_mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/more_stable_windows/priors/cohface_mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/more_stable_windows/priors/cohface_mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/more_stable_windows/priors/cohface_mahnob_target_computable_reliability_windowed.md
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 45 --window-stride-sec 15 --min-support-corr 0.25 --max-support-residual 1.25 --max-files 32 --jobs 8 --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/more_stable_windows/priors/mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/more_stable_windows/priors/mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/more_stable_windows/priors/mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/more_stable_windows/priors/mahnob_target_computable_reliability_windowed.md
cp results/final_operating_point_sensitivity/more_stable_windows/priors/mahnob_target_computable_reliability_windowed.csv results/final_operating_point_sensitivity/more_stable_windows/priors/mahnob_state_component_reliability_windowed.csv
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --out-run results/final_operating_point_sensitivity/more_stable_windows/cohface --reliability-group-csv results/final_operating_point_sensitivity/more_stable_windows/priors/cohface_mahnob_target_computable_reliability_windowed.csv --reliability-prior-scope readout_only
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/mahnob_gt_tailaligned_patch_v1/data --out-run results/final_operating_point_sensitivity/more_stable_windows/mahnob_tailaligned --state-reliability-group-csv results/final_operating_point_sensitivity/more_stable_windows/priors/mahnob_state_component_reliability_windowed.csv --readout-reliability-group-csv results/final_operating_point_sensitivity/more_stable_windows/priors/mahnob_target_computable_reliability_windowed.csv
# Standalone strict regeneration omitted for lean policy: materialization writes strict metrics, and lean may not retain PKL data.
${PY:-python} scripts/run_final_operating_point_sensitivity.py --only more_stable_windows --max-files 32 --jobs 8 --artifact-policy lean

# stricter_cross_family_support: higher agreement requirement; tests whether weak cross-family edges should abstain
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 30 --window-stride-sec 10 --min-support-corr 0.3 --max-support-residual 1 --max-files 32 --jobs 8 --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --dataset-label COHFACE --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/stricter_cross_family_support/priors/cohface_mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/stricter_cross_family_support/priors/cohface_mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/stricter_cross_family_support/priors/cohface_mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/stricter_cross_family_support/priors/cohface_mahnob_target_computable_reliability_windowed.md
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 30 --window-stride-sec 10 --min-support-corr 0.3 --max-support-residual 1 --max-files 32 --jobs 8 --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/stricter_cross_family_support/priors/mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/stricter_cross_family_support/priors/mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/stricter_cross_family_support/priors/mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/stricter_cross_family_support/priors/mahnob_target_computable_reliability_windowed.md
cp results/final_operating_point_sensitivity/stricter_cross_family_support/priors/mahnob_target_computable_reliability_windowed.csv results/final_operating_point_sensitivity/stricter_cross_family_support/priors/mahnob_state_component_reliability_windowed.csv
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --out-run results/final_operating_point_sensitivity/stricter_cross_family_support/cohface --reliability-group-csv results/final_operating_point_sensitivity/stricter_cross_family_support/priors/cohface_mahnob_target_computable_reliability_windowed.csv --reliability-prior-scope readout_only
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/mahnob_gt_tailaligned_patch_v1/data --out-run results/final_operating_point_sensitivity/stricter_cross_family_support/mahnob_tailaligned --state-reliability-group-csv results/final_operating_point_sensitivity/stricter_cross_family_support/priors/mahnob_state_component_reliability_windowed.csv --readout-reliability-group-csv results/final_operating_point_sensitivity/stricter_cross_family_support/priors/mahnob_target_computable_reliability_windowed.csv
# Standalone strict regeneration omitted for lean policy: materialization writes strict metrics, and lean may not retain PKL data.
${PY:-python} scripts/run_final_operating_point_sensitivity.py --only stricter_cross_family_support --max-files 32 --jobs 8 --artifact-policy lean

# looser_cross_family_support: lower agreement requirement; tests whether hard regimes are under-supported
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 30 --window-stride-sec 10 --min-support-corr 0.2 --max-support-residual 1.5 --max-files 32 --jobs 8 --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --dataset-label COHFACE --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/looser_cross_family_support/priors/cohface_mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/looser_cross_family_support/priors/cohface_mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/looser_cross_family_support/priors/cohface_mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/looser_cross_family_support/priors/cohface_mahnob_target_computable_reliability_windowed.md
${PY:-python} scripts/extract_target_reliability_graph_features.py --window-sec 30 --window-stride-sec 10 --min-support-corr 0.2 --max-support-residual 1.5 --max-files 32 --jobs 8 --data-dir results/mahnob_gt_tailaligned_patch_v1/data --dataset-label MAHNOB_tailaligned --out-edge results/final_operating_point_sensitivity/looser_cross_family_support/priors/mahnob_target_reliability_windowed_edges.csv --out-group results/final_operating_point_sensitivity/looser_cross_family_support/priors/mahnob_target_computable_reliability_windowed.csv --out-summary results/final_operating_point_sensitivity/looser_cross_family_support/priors/mahnob_target_computable_reliability_windowed_summary.csv --report-out results/final_operating_point_sensitivity/looser_cross_family_support/priors/mahnob_target_computable_reliability_windowed.md
cp results/final_operating_point_sensitivity/looser_cross_family_support/priors/mahnob_target_computable_reliability_windowed.csv results/final_operating_point_sensitivity/looser_cross_family_support/priors/mahnob_state_component_reliability_windowed.csv
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/20260409_cohface_prod_ofbridge_dofbridge_p1dcons_e2e_policy_narrow/cohface_parh_ossm_prod_ofbridge_dofbridge_p1dcons/data --out-run results/final_operating_point_sensitivity/looser_cross_family_support/cohface --reliability-group-csv results/final_operating_point_sensitivity/looser_cross_family_support/priors/cohface_mahnob_target_computable_reliability_windowed.csv --reliability-prior-scope readout_only
${PY:-python} scripts/materialize_calibrated_multifamily_parh_system.py --name parh_ossm --parh-input multichannel --external-rate-evidence-source ossm_kfstd --enable-observation-law --enable-rate-posterior --enable-target-observability-control --enable-signal-sqi-observability --rate-posterior-output-source final --eval-use-track --max-files 32 --jobs 8 --artifact-policy lean --data-dir results/mahnob_gt_tailaligned_patch_v1/data --out-run results/final_operating_point_sensitivity/looser_cross_family_support/mahnob_tailaligned --state-reliability-group-csv results/final_operating_point_sensitivity/looser_cross_family_support/priors/mahnob_state_component_reliability_windowed.csv --readout-reliability-group-csv results/final_operating_point_sensitivity/looser_cross_family_support/priors/mahnob_target_computable_reliability_windowed.csv
# Standalone strict regeneration omitted for lean policy: materialization writes strict metrics, and lean may not retain PKL data.
${PY:-python} scripts/run_final_operating_point_sensitivity.py --only looser_cross_family_support --max-files 32 --jobs 8 --artifact-policy lean
